

/*
 * Filename: sc_hmi_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_hmi_type.h"



/* USER CODE START SC_HMI_INCLUDE */

/* USER CODE END SC_HMI_INCLUDE */


/*
* description: Signalclass
* name: sc_hmi
* shortname: hmi
*/

/* USER CODE START SC_HMI_USERDEFINITIONS */

/* USER CODE END SC_HMI_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_HMI signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_HMI_driverOut(const SC_HMI_data_t  *const data)
{
	/* USER CODE START driverOutSC_HMI */


	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_HMI */
}



