
/*
 * Filename: sc_pong_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SC_PONG_TYPE
#define _H_DEFINE_SC_PONG_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_PONG_INCLUDES */

/* USER CODE END SC_PONG_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_PONG signal    
 **********************************************************************/

/* USER CODE START SC_PONG_USERDEFINITIONS */

/* USER CODE END SC_PONG_USERDEFINITIONS */

typedef 
/* USER CODE START SC_PONG_SIGNALDATADEFINITION */
struct
{
	
} 
/* USER CODE END SC_PONG_SIGNALDATADEFINITION */
SC_PONG_data_t;

/* USER CODE START InitSC_PONG */

#define SC_PONG_INIT_DATA ((SC_PONG_data_t){})
/* USER CODE END InitSC_PONG */





/* USER CODE START SC_PONG_USERFUNCTIONS */

/* USER CODE END SC_PONG_USERFUNCTIONS */


#endif