

/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_joystick.h"
#include "sc_joystick_type.h"
#include "sc_button.h"
#include "sc_button_type.h"
#include "sc_event.h"
#include "sc_event_type.h"
#include "sc_pong.h"
#include "sc_pong_type.h"
#include "sc_pong.h"
#include "sc_pong_type.h"
#include "sc_pong.h"
#include "sc_pong_type.h"
#include "sc_hmi.h"
#include "sc_hmi_type.h"



/* signal configuration */
/*
* description: A Signal, responsible for Joystick driver behaviour.
* indriver: default
* name: so_joystick
* onDataError: 0
* onDataUpdate: 0
* outdriver: 0
* resource: None
* shortname: joystick
* signalclass: sc_joystick
* signalpool: sp_common
*/

 

static const SC_JOYSTICK_cfg_t SO_JOYSTICK_cfg = 
{
   /* indriver           */  SC_JOYSTICK_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_joystick */


/* signal data */

SC_JOYSTICK_t SO_JOYSTICK_signal= 
{
   /* init value    */  SC_JOYSTICK_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_JOYSTICK_cfg,
}; /* data so_joystick */

/* signal configuration */
/*
* description: A Signal, responsible for button driver.
* indriver: default
* name: so_buttons
* onDataError: 0
* onDataUpdate: 0
* outdriver: 0
* resource: None
* shortname: buttons
* signalclass: sc_button
* signalpool: sp_common
*/

 

static const SC_BUTTON_cfg_t SO_BUTTONS_cfg = 
{
   /* indriver           */  SC_BUTTON_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_buttons */


/* signal data */

SC_BUTTON_t SO_BUTTONS_signal= 
{
   /* init value    */  SC_BUTTON_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_BUTTONS_cfg,
}; /* data so_buttons */

/* signal configuration */
/*
* description: A Signal, responsible for triggering the statemachine.
* indriver: 0
* name: so_event
* onDataError: 0
* onDataUpdate: ev_event_onData
* outdriver: 0
* resource: res_event_Lock
* shortname: event
* signalclass: sc_event
* signalpool: sp_common
*/


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_event_updTasks = { tsk_control };
 

static const SC_EVENT_cfg_t SO_EVENT_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_event_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_event_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  TRUE,
   /* resource           */  res_event_Lock,
   
}; /* configuration so_event */


/* signal data */

SC_EVENT_t SO_EVENT_signal= 
{
   /* init value    */  SC_EVENT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENT_cfg,
}; /* data so_event */

/* signal configuration */
/*
* description: A Signal, containing menue struct. HMI reads out values and positions to print on the hmi
* indriver: 0
* name: so_menue
* onDataError: 0
* onDataUpdate: 0
* outdriver: 0
* resource: None
* shortname: menue
* signalclass: sc_pong
* signalpool: sp_common
*/

 

static const SC_PONG_cfg_t SO_MENUE_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_menue */


/* signal data */

SC_PONG_t SO_MENUE_signal= 
{
   /* init value    */  SC_PONG_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_MENUE_cfg,
}; /* data so_menue */

/* signal configuration */
/*
* description: A Signal
* indriver: 0
* name: so_game
* onDataError: 0
* onDataUpdate: 0
* outdriver: 0
* resource: None
* shortname: game
* signalclass: sc_pong
* signalpool: sp_common
*/

 

static const SC_PONG_cfg_t SO_GAME_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_game */


/* signal data */

SC_PONG_t SO_GAME_signal= 
{
   /* init value    */  SC_PONG_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_GAME_cfg,
}; /* data so_game */

/* signal configuration */
/*
* description: A Signal
* indriver: 0
* name: so_pause
* onDataError: 0
* onDataUpdate: 0
* outdriver: 0
* resource: None
* shortname: pause
* signalclass: sc_pong
* signalpool: sp_common
*/

 

static const SC_PONG_cfg_t SO_PAUSE_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_pause */


/* signal data */

SC_PONG_t SO_PAUSE_signal= 
{
   /* init value    */  SC_PONG_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_PAUSE_cfg,
}; /* data so_pause */

/* signal configuration */
/*
* description: A Signal
* indriver: 0
* name: so_tft
* onDataError: 0
* onDataUpdate: 0
* outdriver: default
* resource: None
* shortname: tft
* signalclass: sc_hmi
* signalpool: sp_common
*/

 

static const SC_HMI_cfg_t SO_TFT_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_HMI_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_tft */


/* signal data */

SC_HMI_t SO_TFT_signal= 
{
   /* init value    */  SC_HMI_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_TFT_cfg,
}; /* data so_tft */



void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_JOYSTICK_incAge( &SO_JOYSTICK_signal, tick); 
   RTE_SC_BUTTON_incAge( &SO_BUTTONS_signal, tick); 
   RTE_SC_EVENT_incAge( &SO_EVENT_signal, tick); 
   RTE_SC_PONG_incAge( &SO_MENUE_signal, tick); 
   RTE_SC_PONG_incAge( &SO_GAME_signal, tick); 
   RTE_SC_PONG_incAge( &SO_PAUSE_signal, tick); 
   RTE_SC_HMI_incAge( &SO_TFT_signal, tick); 
   
}


