

/*
 * Filename: tsk_hmi.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_hmi.h"



/* USER CODE START TSK_HMI_INCLUDE */

/* USER CODE END TSK_HMI_INCLUDE */

#include "swc_pong.h"



/* USER CODE START TSK_HMI_USERDEFINITIONS */

/* USER CODE END TSK_HMI_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_hmi[] = {
    { PONG_hmi_run, ev_hmi_250ms },  //Runnable
}; 
const uint16_t RTE_eventActivation_tsk_hmi_size = sizeof (RTE_eventActivationTable_tsk_hmi) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
* description: Task doing work. Updates HMI Display.
* events: ev_hmi_250ms
* mode: Event
* name: tsk_hmi
* shortname: hmi
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: ev_hmi_250ms
* timertickperiod: 1
*/
TASK(tsk_hmi)
{
    EventMaskType ev = 0;
    
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_hmi_250ms);
        GetEvent(tsk_hmi,&ev);
        ClearEvent(ev);
		
		/* USER CODE START TSK_HMI_TASKBOBY_PRE */

		/* USER CODE END TSK_HMI_TASKBODY_PRE */
    

        //Process Event table on event
        RTE_ProcessEventTable(RTE_eventActivationTable_tsk_hmi, RTE_eventActivation_tsk_hmi_size, ev);
		
		/* USER CODE START TSK_HMI_TASKBODY_POST */

		/* USER CODE END TSK_HMI_TASKBODY_POST */

        
    }
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_HMI_ISR */

/* USER CODE END TSK_HMI_ISR */

