

/*
 * Filename: tsk_input.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_input.h"



/* USER CODE START TSK_INPUT_INCLUDE */

/* USER CODE END TSK_INPUT_INCLUDE */

#include "swc_pong.h"



/* USER CODE START TSK_INPUT_USERDEFINITIONS */

/* USER CODE END TSK_INPUT_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_input[] = {
    { PONG_joy_run, ev_input_10ms },  //Runnable
    { PONG_button_run, ev_input_10ms },  //Runnable
}; 
const uint16_t RTE_eventActivation_tsk_input_size = sizeof (RTE_eventActivationTable_tsk_input) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
* description: Task doing work. Handles input Data. From Joystick, Buttons and whatever should be added in future. Maybe UART.
* events: ev_input_10ms
* mode: Event
* name: tsk_input
* shortname: input
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: ev_input_10ms
* timertickperiod: 1
*/
TASK(tsk_input)
{
    EventMaskType ev = 0;
    
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_input_10ms);
        GetEvent(tsk_input,&ev);
        ClearEvent(ev);
		
		/* USER CODE START TSK_INPUT_TASKBOBY_PRE */

		/* USER CODE END TSK_INPUT_TASKBODY_PRE */
    

        //Process Event table on event
        RTE_ProcessEventTable(RTE_eventActivationTable_tsk_input, RTE_eventActivation_tsk_input_size, ev);
		
		/* USER CODE START TSK_INPUT_TASKBODY_POST */

		/* USER CODE END TSK_INPUT_TASKBODY_POST */

        
    }
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_INPUT_ISR */

/* USER CODE END TSK_INPUT_ISR */

