

/*
 * Filename: sc_joystick_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_joystick_type.h"



/* USER CODE START SC_JOYSTICK_INCLUDE */

/* USER CODE END SC_JOYSTICK_INCLUDE */


/*
* description: Signalclass for game of pong runnables.
* name: sc_joystick
* shortname: joystick
*/

/* USER CODE START SC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SC_JOYSTICK_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_JOYSTICK signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_JOYSTICK_driverIn(SC_JOYSTICK_data_t *const data)
{
	/* USER CODE START driverInSC_JOYSTICK */
    RC_t ret = RC_SUCCESS;
    static uint16_t timeout;
    ADC_Joy_StartConvert();
	//Wait for Conversion
    while(!ADC_Joy_IsEndConversion(ADC_Joy_WAIT_FOR_RESULT)){
        timeout++;
        if(timeout > 1000){
            ret = RC_ERROR_TIME_OUT;
            data->joystick_vertical = 0;
            ADC_Joy_StopConvert();
            goto end;
        }
    }
    data->joystick_vertical = ADC_Joy_GetResult16(1);
    ADC_Joy_StopConvert();
	//Scale it to the application type
    end:

	return RC_SUCCESS;
	/* USER CODE END driverInSC_JOYSTICK */
}



