/* ========================================
 *
 * Copyright YOUR COMPANY, THE YEAR
 * All Rights Reserved
 * UNPUBLISHED, LICENSED SOFTWARE.
 *
 * CONFIDENTIAL AND PROPRIETARY INFORMATION
 * WHICH IS THE PROPERTY OF your company.
 *
 * ========================================
*/

//CONFIGURATION
#define ENABLE_LONG_PRESS_DETECTION 0

#define JOYSTICK_VERTICAL_OFFSET 2180
#define LIMIT_X_HORIZONTAL_TFT_MIN 10
#define LIMIT_X_HORIZONTAL_TFT_MAX 145
#define LIMIT_Y_VERTICAL_TFT_MIN 10
#define LIMIT_Y_VERTICAL_TFT_MAX 90

#define CONTAINER_OUTER_TABLE_SIZE 3
#define WIDGET_OUTER_TABLE_SIZE 3

#define WIDTH_RECTANGLE 30
#define HIGHT_RECTANGLE 5
#define BAT_Y_START_POSITION 50
#define BALL_X_START_POSITION 70
#define BALL_Y_START_POSITION 65
#define BALL_RADIUS 5

#define CURSER_POS_PONG 50
#define CURSER_POS_SNAKE 70
#define CURSER_POS_SOKKER 90
#define CURSER_POS 5
#define CURSER_STEP 20

//DEBUG PURPOSE

#define MONITOR_FILL_LEVEL 0
#define MONITOR_MESSAGEBOX_LOOP 0
#define MONITOR_TYPE 0

#define DEBUG_STATES 0
#define DEBUG_BUTTON_DRIVER 0
#define DEBUG_JOYSTICK_RUNNABLE 0
#define DEBUG_STATEMACHINE_INDEX 0
#define DEBUG_STATEMACHINE 0
#define DEBUG_FUNCTION_PTRS 0

/* [] END OF FILE */
